spring:
#    mysql数据库数据源配置
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/hnebdb
    username: hnebapp
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
# 设置端口
server:
  port: 8080

