spring:
  profiles:
    active: dev #启用application-dev yml文件配置
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  datasource:
    tomcat:
      initial-size: 2
      max-idle: 5
      max-active: 2

server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
    uri-encoding: UTF-8
  session:
    timeout: 1800
  context-path: /
